### ISSUE TITLE
AMI IDs up to date?

### ISSUE THREAD

**Issue by craiig** [amplab/spark-ec2#16]
Just checking if it's known whether or not the AMI IDs are up to date in this repo? I have tried locating the ami ids listed here for us-west-1 and us-west-2, but I could not find the same ids on AWS. The main spark ec2 setup still loads the AMIs from this git repo.

Should I just point the script to use the amazon linux AMI id?

Thanks

**Comment by guang** [comment]
ran into similar problem, would also be interested to know so i could beef up the AMI with python packages

**Comment by shivaram** [comment]
The AMI IDs are up to date as far as I know. AWS search / indexing has some missing entries but you should be able to verify them using the `aws` cli tool with something like 

```
aws ec2 describe-images -r <region> -a <ami-id>
```

**Comment by craiig** [comment]
Yeah, I got around to checking and these still works. FWIW these are old AMIs (2013) with likely lots of security updates to be applied, and it looks like the default ingress rules allow most everything. Be careful! Updating the scripts to newer AMIs would just require changing root to ec2-user. :) Thanks!

**Comment by nchammas** [comment]
> Updating the scripts to newer AMIs would just require changing root to ec2-user.

If by newer AMIs you mean the default Amazon Linux AMIs, then I don't think it's that simple. The spark-ec2 AMIs include a bunch of tools and libraries in specific places that spark-ec2 expects. Also, several commands are run which need root privileges, and they would need to be `sudo`-ed if the user ever changed to something other than root.

If you mean creating a new set of AMIs from the existing spark-ec2 AMIs by applying security updates and making whatever other changes you want, then that would be easier. But then you will likely get stuck with the root user being the default.

If you want to go the route of creating new AMIs from the default Amazon Linux AMIs, you might want to take a look at [these scripts](https://github.com/nchammas/spark-ec2/tree/packer/image-build) I wrote to fully automate that process. I did it using [Packer](https://packer.io/). I haven't updated them since last year since the code never made it into spark-ec2 proper, but you might find it helpful.
